### ISSUE TITLE
Create a GUI for Buggy 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#10]
We need a gui to control the buggy it should be written in java and have the following functionality

Toggle data logging        {ON,RESET,OFF}
Button localization          {RESET}
Toggle use GPS data     {ON, RESET,OFF}
Toggle use Odometry    {ON, RESET, OFF}
Toggle use vision           {ON, RESET, OFF}
Toggle use IMU             {ON, RESET, OFF}
Toggle Time                   {RESET}

Toggle Driver Profile      {Alice}

NOTE: Alice will be the name of are first driver profile she will be a simple way point following driver that is not very aggressive. 

ShowMap of coarse with:
 our believed location super imposed,  
 our   past path super imposed        (button to turn on and off) 
 our  planned path super imposed   (button to turn on and off)
GPS reading marks                          (button to turn on and off)
Encoder reading marks                    (button to turn on and off)
IMU reading marks                           (button to turn on and off)
feature detection's                            (button to turn on and off)

Video Feed (raw)
Video Feed with detection's 
easy way to toggle visual detectors on,off,reset

(NOTE: This would make for a very good 112 project)

**Comment by ramensandwich** [comment]
We have many of these features with the current gui.  Are we ready to close this issue?
