### ISSUE TITLE
Nano_Encoder does not compile due to use Arduino Mega Serial1 in rbserial

### ISSUE THREAD

**Issue by msebek** [CMU-Robotics-Club/RoboBuggy#106]
Repro:
 - Navigate to arduino_src/Nano_encoder
 - $ make
 Get output. Note that Nano_encoder builds to an arduino uno board.

 Error Message:
  ../lib/rbserialmessages/rbserialmessages.cpp:57: error: 'Serial1' was not declared in this scope
  ../Arduino.mk:1038: recipe for target 'build-uno/userlibs/rbserialmessages/rbserialmessages.o' failed
  make: *** [build-uno/userlibs/rbserialmessages/rbserialmessages.o] Error 1

Can't use Serial1 on a board that doesn't have serial1! don't put that in the library pls.

**Comment by ihartwig** [comment]
This is a thing. I probably should have made the ticket when I noticed it.

**Comment by msebek** [comment]
#defines for dayssss

**Comment by TrevorDecker** [comment]
This type of encoder is no longer being used
