### ISSUE TITLE
Repo Needs to be reorganized

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#115]
Our repo needs to be reorganized some of our file structures do not make sense.  We have java_src at the same level as vision system.  What if the vision system uses java?   

I would like to change the structure to be:
RoboBuggy
   - Surface
    - - java_src
   - - C++ src
   - - matlab src
   - arduino 

What do you guys think?

**Comment by TrevorDecker** [comment]
Build18 code also needs to be folded into the rest of the source

**Comment by VasuAgrawal** [comment]
The C++ src and Matlab src are also surface components, right? Based on how you have the dashes I think that is the case, seems like the formatting was a little messed up.

Something like this, right?

- Surface
  - java_src
  - C++ src
  - matlab src
- Arduino
  - Mega
  - Uno
