### ISSUE TITLE
Version Number Check Sum

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#139]
I would like to be able to quickly verify the version of code running on each Arduino.  Can we extend rbms to return a version number or a hash of the date which the code was last modified so that we can verify what version low level is running. 

motivation:
This morning we had what appeared to be  several break deploys from radio time outs.  I know that low level was testing a beta branch  on Friday (voltage reading), as such I could not verify that the code running on the buggy was in the same as last weekend. 

It seems that the problem was electrical but it would still be nice to be able to verify software versions in the future.

**Comment by ramensandwich** [comment]
Resolved with PR #228
