### ISSUE TITLE
Low Level Compile  and Deployment from Surface 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#140]
Can someone add the ability to compile and deploy all parts of low level code from the surface.   I believe the only missing piece is avr gcc.  

This morning we went to reflash  the arduinos but were unable to (I did not bring my computer, and Kevins computer had problems starting up)  It would be really nice to be able to do everything from the surface. 

In hind sight I should have brought my computer, so I take full responsibility for not being able to flash the system.

**Comment by kbrennan234** [comment]
Are we okay with installing VmWare? It should be sufficient for getting the
avr-c compilers.
