### ISSUE TITLE
Record video from web cams (start/stop from gui)

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#142]

**Comment by TrevorDecker** [comment]
The entire gui should be redone

**Comment by kbrennan234** [comment]
I started work on a new gui using JavaFx, but it still needs some work
flushing out the internals. Most of the layouts are similar to what we
currently have, but JavaFx offers more support in developing more
professional looking gui's and 3D drawing tools. Also, it switches to using
css tables for style like in web design.

If you are interested, I can send the code, and you can choose what you
want to take.

**Comment by TrevorDecker** [comment]
That sounds awesome!! Can you make a new branch and push it to the repo? 

Also hope your summer/postgrad life is going well.

**Comment by TrevorDecker** [comment]
This has been implemented in pure java
