### ISSUE TITLE
fix surface mount for old buggy 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#147]

**Comment by TrevorDecker** [comment]
no longer needed as old buggy is being deprecated

**Comment by ramensandwich** [comment]
Are we not keeping old buggy as a testbed?

**Comment by TrevorDecker** [comment]
The main focus this semester will be on transistor. If we come up with a good reason to keep nixi up to date then we can readjust our priorities. But considering the size of our current todo list and the possibly large over head of maintaining a second buggy I think we should focus all efforts towards transistor.

**Comment by VasuAgrawal** [comment]
"nixi"?

**Comment by TrevorDecker** [comment]
Nixi was my name for singularity, nixi tubes were used before transistors.  We used Nixi before transistor.

**Comment by ihartwig** [comment]
Nixi is probably more aptly a predecessor to LEDs than transistors btw. Vacuums tubes aren't the same as nixi tubes.

**Comment by TrevorDecker** [comment]
Ian is correct but "vacuum" or "vacuum tube" doesn't sound as good as a buggy name.  So I am using a small artist license. Keep in mind nixi tubes did come before transistors while the singularity won't happen for many years
