### ISSUE TITLE
add potentiometer to new buggy steering column 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#150]

**Comment by ihartwig** [comment]
Suggested implementation in software: low level should run a "task" that acts as a buggy monitor. This should shut the buggy down (drop brake) if battery is low, pressure is insufficient for braking, lost signal, etc.

**Comment by TrevorDecker** [comment]
@ihartwig what does your comment have to do with a potentiometer being added to the buggy?  Are you suggesting that we have a check to see if the potentiometer disagrees with the command by angle by more then a threshold? 


Right now the servo has been added, mechanical wants to make the mount more secure.  We still need to implement reading the pot in software.

**Comment by TrevorDecker** [comment]
This has been done and we are currently reading values from the potentiometer.
