### ISSUE TITLE
Servo Twitches 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#151]
The new buggy servo started to twitch a lot during the walk around this morning.   This was independent of having the radio receiver plugged in.  So I believe that the problem is coming from the Arduino mega.

**Comment by ramensandwich** [comment]
We didn't seem to have this issue on Saturday night.  Is this while it's receiving signals from the controller?

**Comment by ihartwig** [comment]
I don't believe you, but we can look into it.

**Comment by TrevorDecker** [comment]
This does not seem to be a problem anymore.   Current software has passed testing.  I believe that an electrical problem caused for the ground to wonder giving us a noisy signal
