### ISSUE TITLE
Update the wiki page for programming the transmitter.

### ISSUE THREAD

**Issue by ihartwig** [CMU-Robotics-Club/RoboBuggy#154]
![singularity_transmitter_1](https://cloud.githubusercontent.com/assets/2886013/7100289/ebca7898-dfe5-11e4-82ee-b8e64112c6a0.png)
![singularity_transmitter_2](https://cloud.githubusercontent.com/assets/2886013/7100290/f0dd508a-dfe5-11e4-93d1-05bf759a95c4.png)

**Comment by TrevorDecker** [comment]
Is not an open issue, just to get an image into the system.
