### ISSUE TITLE
Abstractify AVR UART Hardware

### ISSUE THREAD

**Issue by ihartwig** [CMU-Robotics-Club/RoboBuggy#156]
Right now, serial reading drops packets. This is because we spin in a tight loop around waiting for available bytes, but processing each byte takes longer than the time between bytes coming in. This is because the AVR hardware has no serial buffer. Arduino implements a small circular buffer filled by interrupts. We should do something similar.

This is blocked by the part where the UART handlers are hard coded by referring to specific chip registers. We should find a way to abstract this all into a class that can be initialized multiple times to enable more hardware uarts. Arduino has a nice example of this, but there is lots of precompiler magic that turns blocks of code on/off depending on hardware. The instances are also statically defined to names that don't always exist. It would be nice to degrade gracefully.

**Comment by ihartwig** [comment]
@ramensandwich

**Comment by ihartwig** [comment]
avrlib already has a lot of #defines and macros that allow us to access the registers and make interrupts. However, this is not very object oriented. The easiest way I can think of to make this pretty is to pre-allocate buffers and interrupt routines that are enabled based on the hardware selected. Then, an object oriented layer can sit on top that just holds pointers to the static buffers and functions.

Since this is a lot of bit twiddling that depends on specific chips, we can reuse someone else's hard work: https://github.com/andygock/avr-uart

**Comment by TrevorDecker** [comment]
was this fixed with #163  or is it still a problem?

**Comment by TrevorDecker** [comment]
Fixed with new serial reading lib
