### ISSUE TITLE
Implement version numbering in low level systems.

### ISSUE THREAD

**Issue by ihartwig** [CMU-Robotics-Club/RoboBuggy#158]
Spec:
* Create new RBSM message type. Send this message periodically (like we do with the device ID).
* We can use the git short hash (28 bits I think?) + some bits to show if the git workspace is clean or dirty. We can pull the git short hash like this: http://stackoverflow.com/questions/949314/how-to-retrieve-the-hash-for-the-current-commit-in-git
* The makefile should plop this hash into a .h file that is compiled in to the code. This .h should be added to .gitignore so that it is not seen as dirty (lol).

**Comment by ramensandwich** [comment]
Turns out that "git log --pretty=format:'%h' -n 1" also throws in some additional things and breaks the fingerprint.h file.  "git log -1 --format="%h" " seems to work better

**Comment by TrevorDecker** [comment]
This has been merged into master
