### ISSUE TITLE
Simulation engine can generally only support one type of sensor per type of sensor

### ISSUE THREAD

**Issue by VasuAgrawal** [CMU-Robotics-Club/RoboBuggy#165]
In other words, the simulation engine can only handle one concurrent calculated imu. This is due to the sensor channel being used as the hash value. More creative solutions are possible, but deemed unnecessary at the moment.

However, we can have a calculated and faux IMU running together, as well as multiple faux IMUs.

**Comment by TrevorDecker** [comment]
this has been deprecated by the implementation of a new different simulation engine
