### ISSUE TITLE
Pipeline for steer commands from Alice

### ISSUE THREAD

**Issue by VasuAgrawal** [CMU-Robotics-Club/RoboBuggy#166]
It appears that we still need to engineer some sort of solution to allow Alice to directly send steering commands. Currently I believe steer commands are just passed via RBMS.

**Comment by TrevorDecker** [comment]
This task is to set up the control node which will be the node that does all of communicating to low level arduino

**Comment by TrevorDecker** [comment]
I think zach has extended the rbsm node for this to work. It still needs to be tested

**Comment by TrevorDecker** [comment]
This has been implemented
