### ISSUE TITLE
Code cannot compile and run

### ISSUE THREAD

**Issue by ayeohmy** [CMU-Robotics-Club/RoboBuggy#171]
GUI seems to be blocking code from compiling correctly after going through the steps on the debug page in the wiki. Have to look into.

**Comment by TrevorDecker** [comment]
Is this off of master?

**Comment by ayeohmy** [comment]
Yup. Just pulled

**Comment by ayeohmy** [comment]
Managed to compile after commenting out all code related to serial.

**Comment by TrevorDecker** [comment]
This was fixed by master-fix while keeping the serial stuff. This patch is being fixed by @VasuAgrawal  right now.  Will be merged into master once it passes runtime test

**Comment by TrevorDecker** [comment]
fixed by f6ae691a70aaae1f3b30589218b0c86c9fc2a9f5
