### ISSUE TITLE
Lighting system for buggy

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#180]
Lighting system (low level and high level project). Develop a lighting system for the buggy. should have indicator lights for status, blinkers, possibly art, and be easy to change/control from surface.

**Comment by jeremyahuang** [comment]
Merged indicator lighting with interior lighting.

**Comment by ihartwig** [comment]
We already have a bunch of WS2812 lighting strips. We should be able to use them for everything. I've used the https://github.com/cpldcpu/light_ws2812 library before with good success.

**Comment by ramensandwich** [comment]
Implemented in #438
