### ISSUE TITLE
Rework all filepaths to be relative

### ISSUE THREAD

**Issue by VasuAgrawal** [CMU-Robotics-Club/RoboBuggy#189]
Further clarification, when we begin logging, log files are dropped into various places (including in the C:\Users\CurrentUser's directory, which causes adorable fireworks on a mac). These should instead be dropped relative to the repository, since that will always be in the current directory. 

However, these log files should not be committed to the main repo. So 

We have a number of hardcoded filepaths in the code which output log files/debug prints to the local computer's personal directories. This is sub-optimal, since these files are easily ignored/forgotten/deleted. Additionally, this causes errors to be thrown/logs to not be created when switching OS's or computers. 

A better option would be to have log files dropped into the local RoboBuggy directory. These files should not be added to the RoboBuggy repository, however, so .gitignores should be updated to prevent these log files / images / videos from being accidentally added to the repository.

This change is a prereq for Trevor's automatic log uploader.

**Comment by TrevorDecker** [comment]
Vasu do you think you could get this finished in the next week.  Its kind of critical path.

**Comment by VivaanBahl** [comment]
We've finished this, all logs now log to Alice/logs (but aren't checked in)
