### ISSUE TITLE
#define to switch buggies does not actually work

### ISSUE THREAD

**Issue by ihartwig** [CMU-Robotics-Club/RoboBuggy#191]
In commit 42d7194a7cd801050402c9a06d6109d53aec7810 we tried to add support for multiple buggies. That switch doesn't actually work and always uses the first set on constants. My research says this is because the preprocessor doesn't do string comparisons. It sees them all as true, which makes us pick the first if branch. This also doesn't enforce having to set a buggy at all.

Not critical, but we should fix eventually.

We should also set BUGGY=transistor as default.

**Comment by ramensandwich** [comment]
We no longer support multiple buggies (because we only have 1)
