### ISSUE TITLE
Tests for sensors

### ISSUE THREAD

**Issue by VivaanBahl** [CMU-Robotics-Club/RoboBuggy#195]
1) standard tests (can we even receive from sensors)
2) performance tests (if we leave it open for a long time do we continuously get data)
3) data validation (i.e buggy is not in Portugal)
4) find default values for sensors and use as metric for validation
5) put the unit tests in a separate package for Alice

**Comment by msebek** [comment]
Are these supposed to be unit tests (able to run in Travis CI), or testbench (hardware-in-the-loop) tests?

**Comment by TrevorDecker** [comment]
I believe that it is hardware in the loop, @VivaanBahl  is that correct?

**Comment by VivaanBahl** [comment]
Yes, these tests have hardware in the loop
