### ISSUE TITLE
Send compilation information out from arduino

### ISSUE THREAD

**Issue by ihartwig** [CMU-Robotics-Club/RoboBuggy#202]
PR #161 added compilation information in a generated fingerprint.h file. We should make it send the compilation hash number all the time and printf all the information at startup.

**Comment by ramensandwich** [comment]
Does this mean that the Surface will have to be running before the Arduino runs? Or will the information be sent as soon as a connection over UART is made?

**Comment by ihartwig** [comment]
You'll have to be listening when the arduino starts to get the full human-readable dump, but the surface can get the basic information (hash/clean) by the rbsm sent all the time. This will let it check against a known good builds list. It's similar to the rbsm for device id.

**Comment by ramensandwich** [comment]
How are we going to manage the list of good builds? Are we going to create a new file somewhere of roll-ready builds?  Going a little further with that, if no one has any objections, on the high-level side I think we should put up a warning (not error) on the GUI or somewhere visible when we're running a non-approved build

**Comment by TrevorDecker** [comment]
I agree with this, Sean do you feel comfortable doing the high level and
low level portion of this implementation.

On Mon, Oct 5, 2015 at 11:58 AM, Sean Buckley <notifications@github.com>
wrote:

> How are we going to manage the list of good builds? Are we going to create
> a new file somewhere of roll-ready builds? Going a little further with
> that, if no one has any objections, on the high-level side I think we
> should put up a warning (not error) on the GUI or somewhere visible when
> we're running a non-approved build
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CMU-Robotics-Club/RoboBuggy/issues/202#issuecomment-145580545>
> .
>



-- 
Sincerely,

Trevor Decker

**Comment by ramensandwich** [comment]
I'll try to have a build ready this week.  I'll need to bug someone to test it for me though since I don't have easy access to the buggy :)

**Comment by ramensandwich** [comment]
Resolved with PR #228
