### ISSUE TITLE
Managing a file of verified builds

### ISSUE THREAD

**Issue by ramensandwich** [CMU-Robotics-Club/RoboBuggy#212]
Resolution of issue #202 will have the hash of the nearest git commit sent to the high level.  This lays the groundwork for verification of the code we have running on the buggy.  Although we will be able to see the hash printed out, we will have to check the hash to see what we had running.  If we had a scheme to track which commits are "roll ready" or "roll safe" (could be as simple as a text file with a bunch of hashes written in it) and a system to determine what makes a commit "roll safe", then we will be better able to debug issues during rolls.

**Comment by jesseanderson** [comment]
Behavior will be dealt with by completing #179.
