### ISSUE TITLE
Device manger continually resets 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#214]
On the surface the device manger list keeps on reseting making it very difficult to use. We should figure out why and fix the problem.

**Comment by VivaanBahl** [comment]
I've almost never had this happen to me, when does this occur?

**Comment by TrevorDecker** [comment]
This happened last night around 8:00pm when we were preparing to lock the buggy out for the night.  
The need for the device manager will go away with #176. I am still afraid that this is being caused by a larger problem. 

Note everything ran smoothly this morning at rolls.

**Comment by VasuAgrawal** [comment]
Ian and I noted this just a few hours ago as well.

**Comment by TrevorDecker** [comment]
This is still happening?

**Comment by TrevorDecker** [comment]
This happens also happens in windows 10 :(
