### ISSUE TITLE
Add log file checker/message count program 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#215]
Build a script that will count how many times each message type appears in a log file for quick verification at rolls.

**Comment by VivaanBahl** [comment]
Working on this right now in conjunction with #194

**Comment by TrevorDecker** [comment]
@VivaanBahl  has this been finished?

**Comment by VivaanBahl** [comment]
So we now have the data breakdown at the end of all the logs, might be nice to have some utility attached to the stop button that fetches this and displays a dialog

**Comment by TrevorDecker** [comment]
I like this idea, lets add it after last rolls

**Comment by TrevorDecker** [comment]
bump

**Comment by VivaanBahl** [comment]
Finished
