### ISSUE TITLE
log messages sent and received from rbms

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#220]

**Comment by VivaanBahl** [comment]
What messages are there besides the stuff we get from the encoder?

**Comment by ramensandwich** [comment]
Looking at main.cpp, we send the brake state, the auton state, and the battery level.  I'm currently working on also sending the id of the current firmware version (i.e. hash of the nearest commit).

**Comment by VivaanBahl** [comment]
ah gotcha. Basically just add in more nodes on the high level side for receiving all the extra "sensors"

**Comment by ramensandwich** [comment]
Is the addition of new nodes in main.java or Robot.java or somewhere else?

**Comment by TrevorDecker** [comment]
https://github.com/CMU-Robotics-Club/RoboBuggy/wiki/RoboBuggy-Serial-Messages-(RBSM)

**Comment by TrevorDecker** [comment]
This has been implemented but needs to be tested
