### ISSUE TITLE
Encoder feedback delay via RBSM

### ISSUE THREAD

**Issue by VasuAgrawal** [CMU-Robotics-Club/RoboBuggy#222]
With the current version of the code, we're getting about a second of lag between state changes on the encoder - that is, it takes a second for the gui to display that the encoder has started moving (distance is increasing) or similarly that it has stopped (still showing increase for a second after stopping it). Not quite sure where the bug could be -- does this sound like an RBSM problem or something on the high level with RBSMNode?

**Comment by TrevorDecker** [comment]
It is most likely a little bit of both.  For now we can ignore it. We will try to reduce this after logging is done
