### ISSUE TITLE
Catch errors and chuck them into the logs

### ISSUE THREAD

**Issue by VivaanBahl** [CMU-Robotics-Club/RoboBuggy#233]
Now with Trevor's new exception system, we can start to get support for logging any errors we get

**Comment by TrevorDecker** [comment]
I am going to close this as this will be something that we will need to continually do.  I also think that we have caught most of the errors

**Comment by VivaanBahl** [comment]
we need to put them in the logs though (have sensormanager subscribe to the errorpub channel and write the stream)

**Comment by TrevorDecker** [comment]
k can you work on this at some point this week?

**Comment by VivaanBahl** [comment]
sure thing

**Comment by TrevorDecker** [comment]
I think that this has been implemented with the most recent changes of logging @VivaanBahl can you confirm

**Comment by VivaanBahl** [comment]
has been implemented
