### ISSUE TITLE
Allow for multiple cameras to record at the same time 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#269]

**Comment by VasuAgrawal** [comment]
There's infrastructure written for the web gui to publish multiple camera data streams. If you add more cameras to the buggy I can probably get them publishing.

**Comment by TrevorDecker** [comment]
Cool, for now I am focusing on getting the rest of the system running over
multi cams but it's good to design for scale

**Comment by VasuAgrawal** [comment]
If need be we can get a couple webcams hooked up in a few lines, but we won't have logging capability.
