### ISSUE TITLE
Have everything shutdown when the gui is closed

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#280]

**Comment by VivaanBahl** [comment]
I think this works now since I added
this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
to the RobobuggyJFrame in trevor-cleanup

**Comment by VivaanBahl** [comment]
although as Zach suggested last night, we should implement a more graceful shutdown, rather than force-quitting all threads

**Comment by TrevorDecker** [comment]
Shutdown is currently working, we can look into a graceful shutdown later.  But for now the functionality that we want is working.
