### ISSUE TITLE
Add the publisher for brakes in RBSMNode

### ISSUE THREAD

**Issue by VivaanBahl** [CMU-Robotics-Club/RoboBuggy#286]

**Comment by VivaanBahl** [comment]
Right now these are commented out in order for findbugs and checkstyle to run, but these are going to be in use once we establish the channel between the mega and the surface

**Comment by TrevorDecker** [comment]
we should uncomment this

**Comment by VivaanBahl** [comment]
yeah I'll probably get to it when I fill out the big switch statement in RBSMNode

**Comment by TrevorDecker** [comment]
this has been implemented and has been pulled into master
