### ISSUE TITLE
Serial ports "lock up"

### ISSUE THREAD

**Issue by VivaanBahl** [CMU-Robotics-Club/RoboBuggy#306]
When there's an unexpected disconnect while the software is still running, sometimes the serial port will fail to close properly, and thus we can't communicate with anything attached to it, since the OS can't contact it anymore.

**Comment by TrevorDecker** [comment]
see #309

**Comment by TrevorDecker** [comment]
When a serial port is connected and removed several times while Alice is running the port becomes lost to the computer and can not be connected to until after the computer is turned off and back on :(
