### ISSUE TITLE
add finer grain sorting and folder structure for log files

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#308]

**Comment by VasuAgrawal** [comment]
Can you be more specific? Do you want log files sorted on creation, or can there be some utility that splits / sorts them afterward?

**Comment by VivaanBahl** [comment]
Basically we want the log files to be sorted perhaps by date, and then inside of that provide intelligence in sorting them into coursewalks and rolls, rather than have one giant folder with a bunch of log folders lined up

**Comment by TrevorDecker** [comment]
I also think we should have a description of what happened entered by the user at the end of the logging process.
