### ISSUE TITLE
Slow ping to surface

### ISSUE THREAD

**Issue by VasuAgrawal** [CMU-Robotics-Club/RoboBuggy#316]
In testing yesterday, the surface wasn't responding within acceptable margins for ping. Ping varied from 2ms to 3000ms. This is possibly due to a poor router. Determine if new high end hardware is necessary, and if so, find a part number.

**Comment by TrevorDecker** [comment]
It was suggested by @msebek that this problem exists because we are sending too much data across the network. We should rerun this test when only the server is connected but no data is being published

**Comment by VasuAgrawal** [comment]
I'm not sure that's correct. AFAIK we ran this test with the buggy program not running, so the only things on the network should have been the surface and the ping. Will confirm later.

**Comment by TrevorDecker** [comment]
lets re run this test, also we have a new router coming in soonish

**Comment by VasuAgrawal** [comment]
Will re run when the new router comes in. When is the mobile broadband solution expected? we can test with that as well.

**Comment by TrevorDecker** [comment]
router should be in for next rolls, broadband will likely not be ready for
3+ weeks


On Mon, Mar 7, 2016 at 3:06 AM, VasuAgrawal <notifications@github.com>
wrote:

> Will re run when the new router comes in. When is the mobile broadband
> solution expected? we can test with that as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CMU-Robotics-Club/RoboBuggy/issues/316#issuecomment-193146688>
> .
>



-- 
Sincerely,

Trevor Decker

**Comment by VasuAgrawal** [comment]
Cool, I can try to get that tested some time this week if USR isn't bad.
