### ISSUE TITLE
Stop breaking stuff

### ISSUE THREAD

**Issue by VasuAgrawal** [CMU-Robotics-Club/RoboBuggy#336]
Do the thing that I commented on the pull request

**Comment by TrevorDecker** [comment]
this is not a very helpful issue, can you give more details?

**Comment by TrevorDecker** [comment]
bump @VasuAgrawal

**Comment by TrevorDecker** [comment]
If I don't hear a response soon I am just going to close this

**Comment by VivaanBahl** [comment]
@VasuAgrawal please try to write issues that describe the issue fully
