### ISSUE TITLE
GUI Quitting Unexpectedly

### ISSUE THREAD

**Issue by neimandavid** [CMU-Robotics-Club/RoboBuggy#338]
When I run the GUI on my computer, it quits unexpectedly.

The error message on the Java console is:
objc[3019]: Cannot form weak reference to instance (0x7fd89a45e910) of class _CSIRenditionBlockData. It is possible that this object was over-released, or is in the process of deallocation.

(The memory location changes between runs. There's then a bunch of Java stuff saying what looks to be generic "stuff went wrong" information.)

**Comment by ramensandwich** [comment]
If it suggests that the memory location changes between runs, that implies a concurrency issue (i.e. something tried to free an object and another is trying to use it)

**Comment by VasuAgrawal** [comment]
@neimandavid , does this happen every time, or is it a rare occurrence? Can you try trevor-test and see if that produces the same bug?

**Comment by neimandavid** [comment]
I probably won't get around to testing this any time soon, but it was
happening every time I ran the GUI (just at varying times). I don't
remember what I was running (probably my branch and not trevor-test), but
I'll let you know when I get around to testing it.
