### ISSUE TITLE
video files  are corrupted and we need a way to uncorrupt them

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#339]
Many of our video files will become corrupted when they are not closed properly.  For mp4's the data about the file is at the end.  the moov section. 

we need a way to recover these videos.  one solution would be to use avi which saves this data in the beginning.

**Comment by VasuAgrawal** [comment]
Is using a format like avi possible, if we're recording an unknown amount of data?

**Comment by TrevorDecker** [comment]
I think its possible, however mp4's seem to be more space efficient then avi's

**Comment by msebek** [comment]
Proper support for shutdown/close may also solve this?

**Comment by VivaanBahl** [comment]
Yeah because this issue happens when the JVM crashes. If you look at the accompanying log files with these corrupted video files you'll see there's no footer object in the json
