### ISSUE TITLE
Low Level Brake when High Level tells it to

### ISSUE THREAD

**Issue by ramensandwich** [CMU-Robotics-Club/RoboBuggy#349]
This is currently not implemented on master

**Comment by VivaanBahl** [comment]
Bind to #350

**Comment by TrevorDecker** [comment]
@ramensandwich  I think this has been finished, can you verify?

**Comment by TrevorDecker** [comment]
@ramensandwich bump

**Comment by ramensandwich** [comment]
This has been tested and works.
