### ISSUE TITLE
Create Path Planner v 1

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#50]
Write v1 of the path planner, should take in a series of way points and the current location of the buggy.  Depending on what the next reachable point is the desired front angle of the buggy should be set.

**Comment by ramensandwich** [comment]
Once the Trevor-Test branch gets merged into master, we can close this issue

**Comment by TrevorDecker** [comment]
This has been implemented and merged into master
