### ISSUE TITLE
setup unit and system test

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#90]

**Comment by msebek** [comment]
What unit tests should the system have?

- BuggyRos should have functional tests
- BuggyRos should have stress tests
- (fill in more here)

**Comment by TrevorDecker** [comment]
This is going to become very important once we start to run the buggy autonomously, if someone wants to work on it over break you would be my hero.

**Comment by VivaanBahl** [comment]
testing framework has been set up, all that's needed to do is fill it in
