### ISSUE TITLE
Add charts of recent data to gui 

### ISSUE THREAD

**Issue by TrevorDecker** [CMU-Robotics-Club/RoboBuggy#94]
Useful for debugging

**Comment by TrevorDecker** [comment]
We need both xy scatter plots and time series line/bar graphs.

**Comment by VivaanBahl** [comment]
@abhinavGirish and I are investigating the JFreechart library to do this

**Comment by TrevorDecker** [comment]
This has been completed, only needs a little formatting and integration into the main gui.
